version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=scott@example.com
      - PGADMIN_DEFAULT_PASSWORD=tiger
      - PGADMIN_DISABLE_POSTFIX=1
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    networks:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgadmin4/pgpass

networks:
  postgres:

#volumes:
#  postgresql-data:
